### ISSUE TITLE
[Feature request] Display the alt text elsewhere

### ISSUE THREAD

**Issue by David-Guillot** [cwhite92/XKCDBot#12]
Hi,

First of all thank you for this small and efficient app for displaying XKCD on Slack ;)

I have a request though: the alt text is displayed at the top (i.e. before the image) and it often ruins the image joke (since it's more of a complement to the joke). It would be nicer to have it displayed below the image or with a dedicated button.

Thanks!

**Comment by cwhite92** [comment]
Unfortunately I’m quite limited with what I can do here as it leverages the
message formatting API that Slack provides. I’ll see what I can do though.
A button is definitely doable however I’d need a page to redirect the user
to in order to read the alt text.

Thanks for the suggestion!

**Comment by David-Guillot** [comment]
Yes i realized that when i saw [this piece of code](https://github.com/cwhite92/XKCDBot/blob/master/app/Http/Controllers/ComicController.php#L41-L68)... Maybe you could leverage an action button with confirmation dialog, like i did [here](https://api.slack.com/docs/messages/builder?msg=%7B%22attachments%22%3A%5B%7B%22actions%22%3A%5B%7B%22type%22%3A%22button%22%2C%22text%22%3A%22View%20comic%20on%20xkcd.com%22%2C%22url%22%3A%22https%3A%2F%2Fbla.com%22%7D%2C%7B%22name%22%3A%22alt%22%2C%22type%22%3A%22button%22%2C%22text%22%3A%22Show%20Alt%22%2C%22confirm%22%3A%7B%22title%22%3A%22Alt%20text%22%2C%22text%22%3A%22Can%27t%20and%20shouldn%27t%22%2C%22ok_text%22%3A%22OK%22%2C%22dismiss_text%22%3A%22Cancel%22%7D%7D%5D%2C%22image_url%22%3A%22https%3A%2F%2Fimgs.xkcd.com%2Fcomics%2Fcnr.png%22%2C%22fallback%22%3A%22https%3A%2F%2Fbla.com%22%7D%5D%7D)...

**Comment by cwhite92** [comment]
That's certainly an interesting idea. I'll try it out when I have a free moment. :)

**Comment by cwhite92** [comment]
This is now implemented. Thanks for the suggestion @David-Guillot.

**Comment by David-Guillot** [comment]
Awesome man, thanks!
