### ISSUE TITLE
Bing search regex needs to be improved to remove what-if.xkcd.com results

### ISSUE THREAD

**Issue by cwhite92** [cwhite92/XKCDBot#5]
`/xkcd voting` returns this what-if.xkcd.com: http://what-if.xkcd.com/19/

The regex sees that result, parses out the `19` from the URL, and returns comic #19. It should actually ignore what-if.xkcd.com entries.

**Comment by Harry-Torry** [comment]
Can't replicate, should close.

**Comment by cwhite92** [comment]
No longer relevant, XKCDBot uses Google now.
